// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = "";    // Network SSID (name)
const char PASS[]     = "";    // Network password (use for WPA, or use as key for WEP)

void onDurationChange();
void onFrequencyChange();
void onKnobCntChange();
void onIsHighToneChange();

int duration;
int frequency;
int knobCnt;
bool isHighTone;

void initProperties(){

  ArduinoCloud.addProperty(duration, READWRITE, ON_CHANGE, onDurationChange);
  ArduinoCloud.addProperty(frequency, READWRITE, ON_CHANGE, onFrequencyChange);
  ArduinoCloud.addProperty(knobCnt, READWRITE, ON_CHANGE, onKnobCntChange);
  ArduinoCloud.addProperty(isHighTone, READWRITE, ON_CHANGE, onIsHighToneChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
