// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = "";    // Network SSID (name)
const char PASS[]     = "";    // Network password (use for WPA, or use as key for WEP)

int button1_counter;
int button2_counter;
int button3_counter;
int mouseDist;

void initProperties(){

  ArduinoCloud.addProperty(button1_counter, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(button2_counter, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(button3_counter, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(mouseDist, READWRITE, ON_CHANGE);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

